# Generated by Django 2.2.20 on 2021-05-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_instructor_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicreportschedule',
            name='upload_folder_prefix',
            field=models.CharField(default='', help_text='Prefix of the upload folder. In case a prefix ends with a trailing slash,\n        a new folder will be created.\n        ', max_length=254),
        ),
    ]
