# Generated by Django 2.2.20 on 2021-07-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_instructor_reports', '0002_periodicreportschedule_upload_folder_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodicreportschedule',
            name='upload_folder_structure',
            field=models.CharField(choices=[('regular', 'regular'), ('by_date', 'by_date'), ('flat', 'flat')], default='regular', help_text='Define the folder structure during upload.', max_length=32),
        ),
    ]
